apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: postgres-schedule-api
    spec:
      serviceName: "postgres-schedule-api"
      replicas: 1
      selector:
        matchLabels:
          app: postgres-schedule-api
      template:
        metadata:
          labels:
            app: postgres-schedule-api
        spec:
          containers:
            - name: postgres
              image: postgres:15
              env:
                - name: POSTGRES_PASSWORD
                  value: "pass"
                - name: POSTGRES_USER
                  value: "user"
                - name: POSTGRES_DB
                  value: "postgres"
              ports:
                - containerPort: 5432
              volumeMounts:
                - name: data
                  mountPath: /var/lib/postgresql/data
      volumeClaimTemplates:
        - metadata:
            name: data
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi
  - apiVersion: v1
    kind: Service
    metadata:
      name: postgres-schedule-api
    spec:
      selector:
        app: postgres-schedule-api
      ports:
        - port: 5432

  - apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: postgres-prof-assistant
    spec:
      serviceName: "postgres-prof-assistant"
      replicas: 1
      selector:
        matchLabels:
          app: postgres-prof-assistant
      template:
        metadata:
          labels:
            app: postgres-prof-assistant
        spec:
          containers:
            - name: postgres
              image: postgres:15
              env:
                - name: POSTGRES_PASSWORD
                  value: "pass"
                - name: POSTGRES_USER
                  value: "user"
                - name: POSTGRES_DB
                  value: "postgres"
              ports:
                - containerPort: 5432
              volumeMounts:
                - name: data
                  mountPath: /var/lib/postgresql/data
      volumeClaimTemplates:
        - metadata:
            name: data
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi
  - apiVersion: v1
    kind: Service
    metadata:
      name: postgres-prof-assistant
    spec:
      selector:
        app: postgres-prof-assistant
      ports:
        - port: 5432
