apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.telegram: |
    token: $telegram-token

  subscriptions: |
    - recipients: [telegram:-1001829910307]
      triggers: [on-sync-succeeded, on-sync-failed, on-health-degraded, on-deployed]

  template.app-status-template: |
    # Вот этот блок заставит бота писать в нужный топик
    telegram:
      messageThreadId: "6751"
    message: |
      {{ if eq .app.status.operationState.phase "Running" }}⏳{{ else if eq .app.status.sync.status "Synced" }}✅{{ else }}⚠️{{ end }} **App:** {{.app.metadata.name}}
      🔹 **Sync:** {{.app.status.sync.status}}
      🔹 **Health:** {{.app.status.health.status}}
      
      {{ if .app.status.operationState.message }}💬 **Message:** {{.app.status.operationState.message}}{{ end }}
      
      🔗 [Открыть в Argo CD](https://argocd.test.prof-stankin.ru/applications/{{.app.metadata.name}})

  trigger.on-sync-succeeded: |
    - description: Application syncing has succeeded
      send: [app-status-template]
      when: app.status.operationState.phase in ['Succeeded']

  trigger.on-sync-failed: |
    - description: Application syncing has failed
      send: [app-status-template]
      when: app.status.operationState.phase in ['Failed', 'Error']

  trigger.on-health-degraded: |
    - description: Application health is degraded
      send: [app-status-template]
      when: app.status.health.status == 'Degraded'

  trigger.on-deployed: |
    - description: Application is deleted
      send: [app-status-template]
      when: app.metadata.deletionTimestamp != nil
