apiVersion: v1
kind: Secret
metadata:
  name: personal-app-secrets
  namespace: prof-prod-apps
type: Opaque
stringData:
  JWT_SECRET: "super-secret-key-here"
  JWT_SECRET_KEY: "super-secret-key-here"
  AUTH_KEY: "super-secret-key-here"
  ACCESS_TOKEN_SECRET: "super-secret-key-here"
  POSTGRES_PASSWORD: "81!$MTWZ?viv9$f"
  S3_ACCESS_KEY: "8VCZ1KYG145T46I3RYIQ"
  S3_SECRET_KEY: "qxYkAzmPGF1gwh55zmvFAs0WIu8oBROQ2xjRiTyS"
