apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: schedule-db
spec:
  serviceName: "schedule-db-svc"
  replicas: 1
  selector:
    matchLabels:
      app: schedule-db
  template:
    metadata:
      labels:
        app: schedule-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_PASSWORD
              value: "pass"
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: schedule-db-svc
spec:
  selector:
    app: schedule-db
  ports:
    - port: 5432
