apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PROF-Development/k8s-infra.git
    targetRevision: HEAD
    path: infrastructure
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
