apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-project
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-failed.telegram: "-1001829910307:6751"
    notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: "-1001829910307:6751"
    notifications.argoproj.io/subscribe.on-health-degraded.telegram: "-1001829910307:6751"
    notifications.argoproj.io/subscribe.on-deployed.telegram: "-1001829910307:6751"
spec:
  project: default
  source:
    repoURL: https://github.com/PROF-Development/k8s-infra.git
    targetRevision: HEAD
    path: argocd
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
